openapi: 3.0.0
info:
  title: Swagger Petstore - OpenAPI 3.1
  description: "The api docs duh"
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: user
  - name: offer
paths:
  /user/create:
    put:
      tags:
        - user
      summary: Create a user
      description: Create a user, returns a token
      operationId: createUser
      requestBody:
        description: User data
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "Gandalf der Graue"
                  maxLength: 20
                  minLength: 3
                password:
                  type: string
                  example: "Password"
                  maxLength: 20
                  minLength: 3
                location:
                  type: string
                  example: Franz-Mayer-Straße 1, 93053 Regensburg
        required: true
      responses:
        '200':
          description: Created account
          content:
            application/json:
              schema:
                type: string
                example: new-auth-token
                description: The new login token

        '400':
          description: Invalid params
  /offer/list/nearby:
    get:
      tags:
        - offer
      summary: Get all offers near to current location
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"





components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    OfferLocation:
      type: object
      properties:
        id:
          type: string
        lat:
          type: number
        lon:
          type: number
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        petId:
          type: integer
          format: int64
          example: 198772
        quantity:
          type: integer
          format: int32
          example: 7
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          example: approved
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean

security:
  - bearerAuth: []
