openapi: 3.0.0
info:
  title: Swagger Petstore - OpenAPI 3.1
  description: "The api docs duh"
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: user
paths:
  /user/create:
    put:
      tags:
        - user
      summary: Create a user
      description: Create a user, returns a token
      operationId: createUser
      requestBody:
        description: User data
        content:
          application/json:
            schema:
              type: object
              properties:
                location:
                  type: string
                  example: Franz-Mayer-Straße 1, 93053 Regensburg
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema: 
                type: string
                example: fojsdoishfiebrapüfojiodgj
        '400':
          description: Invalid params  
  /user:
    get:
      tags:
        - user
      summary: Get user information
      description: Get user information belonging to token
      operationId: getUser
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid params
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        petId:
          type: integer
          format: int64
          example: 198772
        quantity:
          type: integer
          format: int32
          example: 7
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          example: approved
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
      xml:
        name: order

security:
  - bearerAuth: []
