version: "3.2"
services:
  # server:
  #   image: "redis:alpine"
  #   ports:
  #     - "80:3000"
  db:
    image: postgres
    volumes:
      - "./data:/var/lib/pgsql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=hackburg

